ARG BRANCH=unknown
ARG SRC_FILE=wallet:${BRANCH}
FROM ${SRC_FILE} as wallet
FROM nginx:latest
MAINTAINER toktor <ak.toktor@gmail.com>

COPY --from=wallet /OnyxChain-wallet/build /var/www
COPY ./default.conf /etc/nginx/conf.d
ARG BRANCH=unknown
RUN if [ "${BRANCH}" = "preprod" ] ; then SUFFIX=preprod- ; fi ; sed -i 's/SERVERNAME/'"$SUFFIX"'wallet.onyxpay.co/g' /etc/nginx/conf.d/default.conf

